version: '3'
services:
  app:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: node:latest
    volumes:
      - .:/usr/src/app
    ports:
      - "40081:40081"
    command: bash -c "cd /usr/src/app && npm install && npm start"
    # command: /bin/bash
    restart: always